video_task:
  description: >
    You will recieve {video_frames} as formated base64 encoded images. your just is to identify the key visual elements in the video frames.
    and make sure to summarize it in the end.
  expected_output: >
    A list of key visual elements identified in the video frames.
  agent: visual_analyst

audio_task:
  description: >
    Analyze the audio transcription to extract main points and themes.
  expected_output: >
    A summary of key points from the audio transcription.
  agent: audio_analyst

summary_task:
  description: >
    Combine visual and audio analyses into a comprehensive summary.
  expected_output: >
    A cohesive summary integrating both visual and audio elements. make sure it's in out.md file.
  agent: summary_analyst
